{
  "hash": "1840aec0c0b947ade9c33abd2881c046",
  "result": {
    "markdown": "---\ntitle: \"Multiple Regression <br> Chapter 6.2)\"\ninstitute: \"Department of Statistics and Data Science <br> STAT 202\"\n\nlogo: nu_logo.png\nformat: \n  revealjs:\n    theme: [default, nu_theme.scss]\n    chalkboard:\n      theme: whiteboard\n      toggleNotesButton: false\n    menu:\n        side: right\n    code-line-numbers: false\n\nexecute:\n  message: false\n  warning: false\n  echo: true\n---\n\n\n\n\n## Today's goals {background-image=\"images_comics/correlation.png\" background-size=\"400px\" background-opacity=\"50%\" background-position=\"85% 50%\"}\n\n<br/>\n\n::: columns\n::: {.column width=\"60%\"}\n1.  Multiple regression with one numerical and one categorical variables\n2.  Understand intercept, slope, offset in intercept, and offset in slope\n3.  Parallel slopes vs interaction model\n:::\n:::\n\n## Multiple Regression Goal and Example\n\n**Goal**: build a model with one numerical and one categorical explanatory variable.\n\nUsing the `penguins` dataset, we want to determine how flipper_length impacts body_mass. But we also think body_mass varies by `sex`. Build a model that predicts `body_mass_g` using `flipper_length_mm` and `sex` as explanatory variables. In this dataset `sex` has 2 levels: {male, female}\n\n## Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel~\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse~\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, ~\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, ~\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186~\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, ~\n$ sex               <fct> male, female, female, NA, female, male, female, male~\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n:::\n:::\n\n\n## \"Same slope model\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parallel <- lm(body_mass_g ~ flipper_length_mm + sex, data=penguins)\n\nsummary(model_parallel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = body_mass_g ~ flipper_length_mm + sex, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-910.28 -243.89   -2.94  238.85 1067.73 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -5410.300    285.798 -18.931  < 2e-16 ***\nflipper_length_mm    46.982      1.441  32.598  < 2e-16 ***\nsexmale             347.850     40.342   8.623 2.78e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 355.9 on 330 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.8058,\tAdjusted R-squared:  0.8047 \nF-statistic: 684.8 on 2 and 330 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## Same Slopes Model Output\n\n**Equation**: $\\widehat{bodymass} = -5410.3 + 46.98*flipper + 347.85*\\mathbb{1}_{male}(x)$\n\n-   What is the reference level (baseline) for sex?\n-   Interpretation of $b_0$ : expected value of y for the baseline; the expected body mass for female penguins when flipper length is 0 is -5410.3\n-   Interpretation of $b_1$ : slope of flipper length for both categories\n-   Interpretation of $b_2$ : offset in intercept for males (level = male)\n\n## Same Slopes Model Output\n\n-   You can think of each 'level' having a different line (equation).\n\n-   The equation of the line for penguins who are female (ie: sex = female):\n\n\n$$-5410.3 + 46.98*flipper + 347.85*0$$ $$ -5410.3 + 46.98*flipper$$\n\n\n-   The equation of the line for penguins who are male (ie: sex = male):\n\n\n$$-5410.3 + 46.98*flipper + 347.85*1$$ $$ -5062.45 + 46.98*flipper$$\n\n\n## \"Interaction Model\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_interaction <- lm(body_mass_g ~ flipper_length_mm + sex +flipper_length_mm*sex, data=penguins)\n\nsummary(model_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = body_mass_g ~ flipper_length_mm + sex + flipper_length_mm * \n    sex, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-909.36 -246.58   -3.13  237.18 1065.19 \n\nCoefficients:\n                            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               -5443.9607   440.2829 -12.365   <2e-16 ***\nflipper_length_mm            47.1527     2.2264  21.179   <2e-16 ***\nsexmale                     406.8015   587.3029   0.693    0.489    \nflipper_length_mm:sexmale    -0.2942     2.9242  -0.101    0.920    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 356.4 on 329 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.8058,\tAdjusted R-squared:  0.8041 \nF-statistic: 455.2 on 3 and 329 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## Interaction Model Output\n\n**Equation**: $$\\widehat{bodymass} = -5443.96 + 47.15*flipper + 406.8*\\mathbb{1}_{male}(x) $$ $$- 0.29*flipper*\\mathbb{1}_{male}(x)$$\n\n-   $b_0$ : intercept for baseline\n-   $b_1$ : slope of flipper length for\n-   $b_2$ : offset of intercept for\n-   $b_3$ : offset in slope of flipper length for\n\n## Interaction Model Output\n\nYou can think of each 'level' having a different line (equation).\n\nEquation of the line for female penguins:\n\n<br> <br> Equation of the line for male penguins:\n",
    "supporting": [
      "lec11_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}