project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "STAT 202"
  description: "Homepage for STAT 202"
  site-url: "https://stat202_website.github.io/website/"

  repo-url: https://github.com/dsass1/stat202_website
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  
  sidebar:
    background: "#BBB8B8"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: person-fill
        href: https://campuswire.com/c/G88B46A25
        text: "Campuswire"
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
          - href: index.qmd
            text: Today's agenda
          - href: course-schedule.qmd
            text: Schedule
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Office hours
          - href: course-links.qmd
            text: Useful links

format:
  html:
    theme: cosmo
    toc: true

freeze: auto

editor: visual

