---
title: "Activity Solutions"
---

Activities are graded for completion! It is your responsibility and should be a part of your learning habit to review your activities for correctness.

-   [Solution - textbook exercises](documents/solutions/solution_textbook.html)

-   [Solution - Activity 01](documents/solutions/solution_act_01.html)

-   [Solution - Activity 02](documents/solutions/solution_act_02.html)

-   [Solution - Activity 03](documents/solutions/solution_act_03.html)

-   [Solution - Activity 04](documents/solutions/solution_act_04.html)

-   [Solution - Activity 05](documents/solutions/solution_act_05.html)

-   [Solution - Activity 06](documents/solutions/solution_act_06.html)

-   [Solution - Activity 07](documents/solutions/solution_act_07.html)

-   [Solution - Activity 08](documents/solutions/solution_act_08.html)

-   [Solution - Activity 09](documents/solutions/solution_act_09.html)

-   [Solution - Activity 10](documents/solutions/solution_act_10.html)

-   [Solution - Activity 11](documents/solutions/solution_act_11.html)

-   [Solution - Activity 12](documents/solutions/solution_act_12.pdf)

-   [Solution - Activity 13](documents/solutions/solution_act_13.pdf)

-   [Solution - Activity 14](documents/solutions/solution_act_14.pdf)

-   [Solution - Activity 15](documents/solutions/solution_act_15.pdf)

-   [Solution - Activity 16](documents/solutions/solution_act_16.pdf)

<!-- -   [Solution - Activity 17](documents/solutions/solution_act_17.html) -->

<!-- -   [Solution - Activity 18](documents/solutions/solution_act_18.html) -->

<!-- -   [Solution - Activity 19](documents/solutions/solution_act_19.html) -->

<!-- -   [Solution - Activity 20](documents/solutions/solution_act_20.html) -->
