---
title: "Today's Agenda"
editor_options: 
  chunk_output_type: console
execute:
  message: false
  warning: false
  echo: false
---

<!-- ::: callout-important -->
<!-- Classes are virtual this week. -->
<!-- Find Zoom links -->
<!-- ::: -->


```{r}
library(tidyverse)
library(gt)
today_ymd <- Sys.Date()
today <- format(today_ymd,"%a %b %d")


agenda_final <- read_csv("documents/agenda_final.csv")%>% 
  mutate(time = today_ymd - date_ymd)

val <- ifelse(max(agenda_final$time)<0,
              max(agenda_final$time),
              min(agenda_final$time[agenda_final$time>=0]) )


agenda_today <- agenda_final %>% filter(time == val)

```

## <span style="color: #4E2A84;"> Class:  `r agenda_today$Date` </span> 

```{r}
agenda_today %>% 
  select(callout) %>% 
  mutate(callout = ifelse(!is.na(callout), map(paste0({fontawesome::fa('triangle-exclamation')}, callout), glue::glue), "NA")) %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(V1 != "NA") %>% 
  gt() %>% 
  fmt_markdown(columns = c(V1) )%>%
  cols_align(align = "left") %>% 
  tab_options(column_labels.hidden = TRUE,
              table.align = "left",
              table_body.border.top.color = "white",
              table_body.border.bottom.color = "white",
              table_body.hlines.color = "white",
              table.width = pct(100))
```


## Prepare

```{r}
agenda_today %>% 
  select(Reading) %>% 
  mutate(Reading = ifelse(!is.na(Reading), map(paste0({fontawesome::fa('book-open')} ," Read ", Reading), glue::glue), "NA")) %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(V1 != "NA") %>% 
  gt() %>% 
  fmt_markdown(columns = c(V1) )%>%
  cols_align(align = "left") %>% 
  tab_options(column_labels.hidden = TRUE,
              table.align = "left",
              table_body.border.top.color = "white",
              table_body.border.bottom.color = "white",
              table_body.hlines.color = "white",
              table.width = pct(100))
```

<br>

## Agenda

```{r}
agenda_today %>% 
  select(agenda1, agenda2, agenda3, agenda4, Slides, Activity) %>% 
  mutate(Slides = ifelse(!is.na(Slides), map(paste0("Section notes: ", Slides), glue::glue), "NA"),
         Activity = ifelse(!is.na(Activity), map(paste0("Daily activity: ", Activity), glue::glue), "NA"),
         agenda1 = map(agenda1, glue::glue),
         agenda2 = map(agenda2, glue::glue),
         agenda3 = map(agenda3, glue::glue),
         agenda4 = map(agenda4, glue::glue)) %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(V1 != "NA") %>% 
  gt() %>% 
  fmt_markdown(columns = c(V1) )%>%
  cols_align(align = "left") %>% 
  tab_options(column_labels.hidden = TRUE,
              table.align = "left",
              table_body.border.top.color = "white",
              table_body.border.bottom.color = "white",
              table_body.hlines.color = "white",
              table.width = pct(100))

```


## Homework Due `r agenda_today$due` 11:59pm

```{r}
agenda_today %>% 
  select(submit_act,reading_hw, Tutorial, Project) %>% 
  mutate(submit_act = ifelse(!is.na(submit_act), map(paste0("Complete and submit ", submit_act), glue::glue), "NA"), 
         reading_hw = ifelse(!is.na(reading_hw), map(paste0({fontawesome::fa('book-open')} ," Read ", reading_hw), glue::glue), "NA"),
         Tutorial = ifelse(!is.na(Tutorial), map(paste0("Complete and submit ", Tutorial), glue::glue), "NA"),
         Project = ifelse(!is.na(Project), map(paste0("Complete and submit ", Project), glue::glue), "NA") ) %>% 
  t() %>% 
  as.data.frame() %>% 
  filter(V1 != "NA") %>% 
  gt() %>% 
  fmt_markdown(columns = c(V1) )%>%
  cols_align(align = "left") %>% 
  tab_options(column_labels.hidden = TRUE,
              table.align = "left",
              table_body.border.top.color = "white",
              table_body.border.bottom.color = "white",
              table_body.hlines.color = "white",
              table.width = pct(100))

```


<br><br>

```{r echo = FALSE}
knitr::knit_exit()
```
