---
title: "Repeated Sampling (9.5-9.6)"
format: revealjs
editor: visual
---


## The Reality

We are never going to take thousands of samples and construct a sampling distribution. The concept of random sampling is entirely theoretical and lays the foundations for the derivations of the standard errors in Table 9.6.

## Central Limit Theorem

A **sampling distribution** of a mean ($\bar{x})$ will get closer and closer to the normal curve as the number of repetitions increases. This is true no matter the shape of the original data!  

-   The mean of your sampling distribution is the same as the population mean. $mean(\bar{x}) = \mu$. 

-   The standard error of your sampling distribution is less than the spread of the population. $SE(\bar{x}) = \frac{\sigma}{\sqrt{n} }$
    
$$\bar{x} \sim N\left(\mu_{\bar{x}} = \mu_x, SE(\bar{x})= \frac{\sigma_x}{\sqrt{n}}\right)$$


## What makes a good sample?

-   representative of the population
-   picked at random (avoids bias)
-   big enough size to draw conclusions from ($n \geq 30$)
-   independent samples - includes less than 10\% of the population (too big of a sample $n$ will create dependence between samples)
-   Exception: If the population is already normal, the results hold for samples of any size $n$


