{
  "hash": "4ce387f9f225badda93f55146604c45e",
  "result": {
    "markdown": "---\ntitle: \"Multiple Regression <br> Chapter 6.0 - 6.1\"\ninstitute: \"Department of Statistics and Data Science <br> STAT 202\"\n\nlogo: nu_logo.png\nformat: \n  revealjs:\n    theme: [default, nu_theme.scss]\n    chalkboard:\n      theme: whiteboard\n      toggleNotesButton: false\n    menu:\n        side: right\n    code-line-numbers: false\n\nexecute:\n  message: false\n  warning: false\n  echo: true\n---\n\n\n\n\n## Today's goals {background-image=\"images_comics/graphing_relationship.png\" background-size=\"400px\" background-opacity=\"50%\" background-position=\"85% 50%\"}\n\n<br/>\n\n::: columns\n::: {.column width=\"60%\"}\n1.  Regression with two numerical explanatory variables\n2.  Understand coefficient interpretation\n3.  Make predictions with a model\n:::\n:::\n\n## Multiple Regression\n\n**Definition**: models the relationship between a response (y) variable and two or more explanatory (x) variables.\n\n-   2 numerical explanatory variables this is the \"plane\" of best fit.\n-   1 numerical + 1 categorical explanatory variable use a line of best fit separated by category.\n\n**EDA**: Same as simple regression. Look at the raw data, calculate summary statistics/correlations, and use data visualizations.\n\n## MLR Correlation and Causation\n\n**Correlation**: calculate the correlation between each pair of variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins %>% \n  filter(!is.na(flipper_length_mm)) %>% \n  select(body_mass_g, flipper_length_mm, bill_length_mm) %>%\n  cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  body_mass_g flipper_length_mm bill_length_mm\nbody_mass_g         1.0000000         0.8712018      0.5951098\nflipper_length_mm   0.8712018         1.0000000      0.6561813\nbill_length_mm      0.5951098         0.6561813      1.0000000\n```\n:::\n:::\n\n\n<br>\n\n**Causation**: any change in the value of one variable will cause a change in the value of another variable, which means one variable makes the other happen.\n\n## Correlation does not mean causality!!\n\n<center>![](images_lecture/icecream_drownings.png){#id .class width=\"650px\" height=\"600px\"}</center>\n\n## Multiple Regression Modeling\n\nMultiple regression is the procedure that helps us disentangle issues with confounding (lurking) variables. That is, a procedure that will help sort out collinearity issues.\n\n-   **Simpson's paradox**: a trend appears in several groups of data but the trend disappears or reverses when groups are combined.\n\n-   **Model**: In multiple linear regression, the significance of each term in the model depends on the other terms in the model.\n\n## Example: model\n\nPredict body mass based on both flipper length and bill length.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_penguins <- lm(body_mass_g ~ flipper_length_mm + bill_length_mm, data = penguins)\nsummary(model_penguins)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      Estimate Std. Error    t value     Pr(>|t|)\n(Intercept)       -5736.897161 307.959128 -18.628762 7.796205e-54\nflipper_length_mm    48.144859   2.011115  23.939388 7.564660e-75\nbill_length_mm        6.047488   5.179831   1.167507 2.438263e-01\n```\n:::\n:::\n\n$$\\widehat{bodymass} = b_0 +b_1*\\text{flipper} + b_2*\\text{bill_length}$$\n\n\n## Example: interpretations\n\n\n$$\\widehat{bodymass} = -5736.9 + 48.14*\\text{flipper} + 6.05*\\text{bill_length}$$\n\n\n-   $b_0$: intercept; the **predicted/expected** body mass when a penguin has flipper length 0 and bill length 0\n-   $b_1$: slope of flipper length; taking into account all other explanatory variables, for every 1 mm increase in flipper length, the **expected** body mass increases by $48.14$\n-   $b_2$: slope of bill length; taking into account all other explanatory variables, for every 1 mm increase in bill length, the **expected** body mass increases by $6.05$\n",
    "supporting": [
      "lec10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}