{
  "hash": "6dddfcc142f2b0131ac17a51ad3a4c5b",
  "result": {
    "markdown": "---\ntitle: \"Regression <br> Chapter 5.2 - 5.4\"\ninstitute: \"Department of Statistics and Data Science <br> STAT 202\"\n\nlogo: nu_logo.png\nformat: \n  revealjs:\n    theme: [default, nu_theme.scss]\n    chalkboard:\n      theme: whiteboard\n      toggleNotesButton: false\n    menu:\n        side: right\n    code-line-numbers: false\n\nexecute:\n  message: false\n  warning: false\n  echo: true\n---\n\n\n\n\n\n## Today's goals {background-image=\"images_comics/last_line_defense.png\" background-size=\"400px\" background-opacity=\"50%\" background-position=\"85% 50%\"}\n\n<br/>\n\n::: columns\n::: {.column width=\"60%\"}\n1.  Regression model with single categorical explanatory variable\n2.  Understand what an offset is\n:::\n:::\n\n## Simple Categorical Linear Regression\n\n-   **Definition**: Simple Categorical Linear Regression models the relationship between a response (y) variable and one categorical explanatory (x) variable.\n\n\n- Now the model will give us differences by **categories** relative to a **baseline** for comparison.\n\n## Example {auto-animate=\"true\" .scrollable}\n\nConsider the Palmer Penguins dataset. \n\nWe want to use `species` to predict `body_mass_g`. In other words we think penguins body mass varies by species.\n\nRecall our dataset has 3 species: Adelie, Gentoo, Chinstrap\n\n\n::: panel-tabset\n\n## Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Build a model\nmodel_species <- lm(body_mass_g ~ species, data = penguins)\n```\n:::\n\n\n## Data\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel~\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse~\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, ~\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, ~\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186~\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, ~\n$ sex               <fct> male, female, female, NA, female, male, female, male~\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n:::\n:::\n\n\n:::\n\n\n## Example {auto-animate=\"true\" .scrollable}\n\nConsider the Palmer Penguins dataset. \n\nWe want to use `species` to predict `body_mass_g`. In other words we think penguins body mass varies by species.\n\nRecall our dataset has 3 species: Adelie, Gentoo, Chinstrap\n\n\n::: panel-tabset\n\n## Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Build a model\nmodel_species <- lm(body_mass_g ~ species, data = penguins)\n\nsummary(model_species)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = body_mass_g ~ species, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1126.02  -333.09   -33.09   316.91  1223.98 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       3700.66      37.62   98.37   <2e-16 ***\nspeciesChinstrap    32.43      67.51    0.48    0.631    \nspeciesGentoo     1375.35      56.15   24.50   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 462.3 on 339 degrees of freedom\n  (2 observations deleted due to missingness)\nMultiple R-squared:  0.6697,\tAdjusted R-squared:  0.6677 \nF-statistic: 343.6 on 2 and 339 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## Data\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel~\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse~\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, ~\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, ~\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186~\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, ~\n$ sex               <fct> male, female, female, NA, female, male, female, male~\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n:::\n:::\n\n\n:::\n\n## Regression Equation {.scrollable}\n\nBelow is the summary output.\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_species)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   Estimate Std. Error    t value      Pr(>|t|)\n(Intercept)      3700.66225   37.61935 98.3712321 2.488024e-251\nspeciesChinstrap   32.42598   67.51168  0.4803018  6.313226e-01\nspeciesGentoo    1375.35401   56.14797 24.4951686  5.420612e-77\n```\n:::\n:::\n\n\nWhat is the **baseline** species?\n\n<br>\n\nWhat is the regression equation?\n\n\n\n\n## Indicator function {.scrollable}\n\nWill take on either the value of \"1\" or \"0\" depending if the condition is true.\n\n\\begin{equation}\n\\mathbb{1}_{gentoo}(x) = \\begin{cases}\n        1 & \\text{if x is Gentoo}\\\\\n        0 & \\text{if x is NOT Gentoo}\n    \\end{cases}\n\\end{equation}\n\n<br>\n\nConsider 3 randomly sampled Penguins below.\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 x 7\n  species island    bill_length_mm bill_depth_mm flipper_length_mm body_~1 sex  \n  <fct>   <fct>              <dbl>         <dbl>             <int>   <int> <fct>\n1 Gentoo  Biscoe              41.7          14.7               210    4700 fema~\n2 Adelie  Torgersen           45.8          18.9               197    4150 male \n3 Gentoo  Biscoe              45.1          14.4               210    4400 fema~\n# ... with abbreviated variable name 1: body_mass_g\n```\n:::\n:::\n\n\nWhen using the model equation which of the penguins would you set $\\mathbb{1}_{gentoo}(x) = 1?$ What about $\\mathbb{1}_{chinstrap}(x) = 1?$\n\n## Interpretation {.scrollable}\n\n\n$$\\widehat{bodymass} = b_0 + b_1*\\mathbb{1}_{chinstrap}(x)+ b_2*\\mathbb{1}_{gentoo}(x)$$\n\n\n-   Interpretation of $b_0$: expected value of y for the baseline; the expected body mass for Adelie species is 3700.7\n-   Interpretation of $b_1$ : offset in intercept; expected body mass for Chinstrap species is 32.4 **more** on **average** than Adelie species\n-   Interpretation of $b_2$ : offset in intercept; expected body mass for Gentoo species is 1375.4 **more** on **average** than Adelie species.\n\n\n-   Which penguin species weighs the least **on average**?\n\n-   Which penguin species weighs the most **on average**?\n\n## Extra information\n\n- There will always be $n-1$ coefficients for the categorical variable, where $n$ is the number of categories.\n\n  - The penguins had 3 species categories so there were 2 species coefficients.\n\n- Categorical variable coefficients will always be an **offset** to either the intercept or slope. Because you can't multiply 32.42*gentoo!\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n\r\n      // dispatch for htmlwidgets\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for reveal\r\n    if (window.Reveal) {\r\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\r\n        fireSlideChanged(event.previousSlide, event.currentSlide);\r\n      });\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}